export const LOADING = "LOADING";
export const GET_ESTIMATE_LIST = "GET_ESTIMATE_LIST";
export const GET_ESTIMATE_LIST_DETAIL = "GET_ESTIMATE_LIST_DETAIL";
export const GET_ESTIMATE_LIST_COUNT = "GET_ESTIMATE_LIST_COUNT";
export const GET_INSPECTION_DETAIL = "GET_INSPECTION_DETAIL";


// Inspection constants
export const GET_INSPECTION_LIST = "GET_INSPECTION_LIST";
export const GET_INSPECTION_LIST_DETAIL = "GET_INSPECTION_LIST_DETAIL";
export const GET_INSPECTION_CATALOG_MASTER = "GET_INSPECTION_CATALOG_MASTER";
export const GET_INSPECTION_CATALOG_SUMMARY = "GET_INSPECTION_CATALOG_SUMMARY";

export const GET_MASTER_DATA_CHECKPOINTS = "GET_MASTER_DATA_CHECKPOINTS";
export const SET_ESTIMATE_FORM_DATA = "SET_ESTIMATE_FORM_DATA";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_ERROR_ALERT = "SET_ERROR_ALERT";
export const SAVE_ESTIMATES = "SAVE_ESTIMATES";

export const GET_WORK_ORDER_LIST = "GET_WORK_ORDER_LIST";

// Yard constants
export const GET_YARD_QA_LIST = "GET_YARD_QA_LIST";
export const GET_YARD_QA_LIST_COUNT = "GET_YARD_QA_LIST_COUNT";
export const APPROVE_REJECT_QUALITY_CHECK = "APPROVE_QUALITY_CHECK";
export const GET_LAST_INSPECTION_DATA = "GET_LAST_INSPECTION_DATA";
export const GET_MASTER_DATA_QC_IMAGES_KEYS = "GET_MASTER_DATA_QC_IMAGES_KEYS";

export const GET_WORKSHOP_QA_LISTING = "GET_WORKSHOP_QA_LISTING";
export const GET_WORKSHOP_QA_LISTING_COUNT = "GET_WORKSHOP_QA_LISTING_COUNT";
export const GET_WORKSHOP_QA_LISTING_DETAILS = "GET_WORKSHOP_QA_LISTING_DETAILS";
export const ACTION_MASTERDATA_START = "ACTION_MASTERDATA_START";
export const STORE_LOCATIONS = "STORE_LOCATIONS";
export const ACTION_MASTERDATA_END = "ACTION_MASTERDATA_END";
export const LOADER_HANDLER = "LOADER_HANDLER";
export const ASSIGN_APPOINTMENT_ID = "ASSIGN_APPOINTMENT_ID";

export const GET_APPOINTMENT_SEARCH_RESULT = "GET_APPOINTMENT_SEARCH_RESULT";
export const GET_YARD_LISITNG_DATA = "GET_YARD_LISITNG_DATA";
export const GET_YARD_LISITNG_DETAILS_DATA = "GET_YARD_LISITNG_DETAILS_DATA";
export const GET_INSPECTION_HISTORY_LISTING = "GET_INSPECTION_HISTORY_LISTING";
export const GET_INSPECTION_HISTORY_LISTING_DETAILS =
  "GET_INSPECTION_HISTORY_LISTING_DETAILS";
export const GET_ESTIMATE_LISTING = "GET_ESTIMATE_LISTING";
export const GET_ESTIMATE_LISTING_DETAIL = "GET_ESTIMATE_LISTING_DETAIL";
export const GET_INSPECTION_SUMMARY = "GET_INSPECTION_SUMMARY";
