export const LOADING = "LOADING";
export const GET_ESTIMATE_LIST = "GET_ESTIMATE_LIST";
export const GET_ESTIMATE_LIST_DETAIL = "GET_ESTIMATE_LIST_DETAIL";
export const GET_MASTER_DATA_CHECKPOINTS = "GET_MASTER_DATA_CHECKPOINTS";
export const SET_ESTIMATE_FORM_DATA = "SET_ESTIMATE_FORM_DATA";
export const SET_LANGUAGE = "SET_LANGUAGE";
